name: research1-run
run-name: research1-run (${{ inputs.run_tag }})

on:
  workflow_dispatch:
    inputs:
      run_tag:
        description: "Unique tag for this run (e.g. fr-20251027-1)"
        required: true
        default: local-1
        type: string
      args:
        description: "All CLI flags as a single string (e.g. --countries FR --results-per-page 50 ...)"
        required: true
        default: ""
        type: string
      countries:
        description: "Comma list of countries (e.g. FR,DE)"
        required: true
        default: ""
        type: string


jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v4

      - name: Checkout private runner repo
        uses: actions/checkout@v4
        with:
          repository: fpart2/research1-runner
          token: ${{ secrets.PRIVATE_REPO_PAT }}
          path: runner

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f runner/requirements.txt ]; then pip install -r runner/requirements.txt; fi

      - name: Run task
        timeout-minutes: 330   # ~5.5h, leaves time to package/upload before GH kills at 6h
        run: |
          mkdir -p out
          # All flags come in via ${{ inputs.args }}
          python runner/research1_task.py --out out ${{ inputs.args }}

      - name: Prune already-have files
        if: always()
        run: |
          set -e
          HAVE_GZ="runner/state/${{ inputs.run_tag }}/have.txt.gz"
          mkdir -p /tmp
          if [ -f "$HAVE_GZ" ]; then
            gunzip -c "$HAVE_GZ" | sed 's/\r$//' | sort -u > /tmp/have.txt
          else
            : > /tmp/have.txt
          fi

          # Build list ONLY from requested countries (not everything in out/)
          CCS="$(echo "${{ inputs.countries }}" | tr ',' ' ' | tr '[:lower:]' '[:upper:]')"
          : > /tmp/all.txt
          if [ -d "out" ]; then
            for c in $CCS; do
              if [ -d "out/$c" ]; then
                ( cd out && find "$c" -type f -name '*.json' -print ) >> /tmp/all.txt
              fi
            done
          fi
          sort -u /tmp/all.txt -o /tmp/all.txt

          # Remove files that we already have locally (duplicates)
          comm -12 /tmp/all.txt /tmp/have.txt > /tmp/dups.txt || true
          while IFS= read -r rel; do
            [ -n "$rel" ] && rm -f "out/$rel" || true
          done < /tmp/dups.txt

      - name: Package artifacts (per country directory)
        if: always()
        run: |
          mkdir -p artifacts
          cd out 2>/dev/null || exit 0

          CCS="$(echo "${{ inputs.countries }}" | tr ',' ' ' | tr '[:lower:]' '[:upper:]')"
          for d in $CCS; do
            if [ -d "$d" ] && find "$d" -type f -name '*.json' -print -quit | grep -q . ; then
              zip -r "../artifacts/${d}.zip" "$d"
            fi
          done

          # Also include partition state files so you can resume precisely
          if ls state_*.json >/dev/null 2>&1; then
            zip -r ../artifacts/state_json.zip state_*.json
          fi

          cd -

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: research1-output-${{ inputs.run_tag }}
          path: artifacts/*.zip
          if-no-files-found: ignore
          compression-level: 0
